- packages/nextjs/components/simpleNFT/MyHoldings.tsx
- packages/nextjs/components/simpleNFT/NFTCard.tsx
> Fix NFTs container size

- packages/nextjs/next.config.js
- packages/nextjs/package.json
See https://github.com/scaffold-eth/se-2-challenges/issues/35#issuecomment-1657808264
When merged, we should back-merge this to all the existing challenge branches
> Ignore typescript/eslint errors on build

- README.md
- packages/hardhat/deploy/01_deploy_vendor.ts
- packages/nextjs/pages/events.tsx
- packages/nextjs/pages/token-vendor.tsx
- General updates to the ReadMe
- Buy Events are now uncommented in events.tsx
- Vendor.sol no longer inherits Ownable, instructions added to ReadMe
- Divided vendor deploy script into sections to match the ReadMe
I plan to iterate on the ReadMe once again after merging since these changes were made in an IDE.
> Challenge 2 - Updates

- README.md
- packages/nextjs/pages/events.tsx
1 . Added the SellToken UI : 
2 . Updated the logic so that once the user uncomments we show Event Title  and loading instead of just showing loaders without titles : 
3 . Updated the ReadMe for the same 
tackles pt.5 of #41
> chall-2/add SellToken UI 

- packages/nextjs/package.json
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConnectors.tsx
- yarn.lock
fixes sepolia network error https://github.com/scaffold-eth/se-2-challenges/issues/37
copied https://github.com/scaffold-eth/scaffold-eth-2/pull/381
> fix: sepolia and wc2

- packages/nextjs/components/SwitchTheme.tsx
> fix: theme toggle styles

- packages/nextjs/components/SwitchTheme.tsx
- packages/nextjs/package.json
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConnectors.tsx
- yarn.lock
Back-merged recent 2 PR's #47 & #46 
Commands used : 
```
git merge --squash base-challenge-template
```
There were conflicts in `yarn.lock` , I discarded all the changes from `yarn.lock` and ran "yarn install" and this correctly updated `yarn.lock` similar to #47 checkout #47 `yarn.lock` file changes here -> https://github.com/scaffold-eth/se-2-challenges/pull/47/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de
Like if there are merge conflicts in `yarn.lock` doing `yarn install` resolves them automatically but just to be sure I did above thing since we have updated packages in `package.json` 🙌
> chall-0/back-merge base-challenge-template

- README.md
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/SwitchTheme.tsx
- packages/nextjs/package.json
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConnectors.tsx
- yarn.lock
Checkout #49 for more description
> back-merge base-template using : git merge --squash

- packages/nextjs/components/SwitchTheme.tsx
- packages/nextjs/package.json
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConnectors.tsx
- yarn.lock
Check #49, but this didn't have merge-conflicts in yarn.lock 🙌
> back-merge base-challenge-template using : git merge --squash

- README.md
- packages/hardhat/contracts/DEX.sol
**Changes**
- A handful of ReadMe wording updates and some additions/deletions. Feel free to discuss.
- Slight wording change in DEX.sol comments since we are not including a solutions file with this challenge.
**Other thoughts**
- It is unclear to me what this line is saying and what exactly to do.  Any ideas on how to clean this up?
_💡 Hints: See this [link](https://hackernoon.com/formulas-of-uniswap-a-deep-dive), solve for the change in the Output Reserve. See the section in that link up to the uniswap v3 title._
- Do we still need this line?  It is kind of a bummer that if they are seeing this, they likely did a copy/paste job in the challenge.
_It is okay if it says your contract is already verified. Copy the addresses of BAL.sol and DEX.sol and search them on sepolia Etherscan to …
> Challenge 4 dex

- packages/hardhat/contracts/Streamer.sol
- packages/hardhat/deploy/00_deploy_streamer.ts
- Cleaned the comments in the deploy file.
- Cleaned comments in the contract.
Fixes #60
> Clean comments in deploy file and contract

- packages/nextjs/pages/events.tsx
> Challenge 4 - Fix column data order in Liquidity Events (eth and balloons where switched)

- README.md
Fixes #57  [last task](https://github.com/scaffold-eth/se-2-challenges/issues/57#issuecomment-1679889573)
> Challenge 0 - Update README to remove the copy/paste from the yarn deploy command

- README.md
Added some information for beginners to describe what "yarn generate" command do
> Challenge-0-simple-nft

- README.md
Update burner wallet config variable on Readme.
> Challenge 2: Modify burner wallet config explanation on Readme #82

- README.md
Update burner wallet config variable on Readme.
> Challenge 5: Modify burner wallet config explanation on Readme

- packages/nextjs/utils/scaffold-eth/fetchPriceFromUniswap.ts
Just back-merging this which we found at https://github.com/scaffold-eth/se-2-challenges/pull/84#issuecomment-1716159180 🙌
> fix 0 ETH price on sepolia network

- packages/nextjs/components/Header.tsx
- packages/nextjs/package.json
- packages/nextjs/utils/scaffold-eth/fetchPriceFromUniswap.ts
- yarn.lock
1. Locked the version of `next` for now checkout #90 for more description, fixes #89 
2. Fix eth price as 0 on sepolia #85 
3. Also fixed navlinks Icon and text breaks when deployed  we fixed this in SE-2 at https://github.com/scaffold-eth/scaffold-eth-2/pull/510 (need to update this on other branches too 🙌)
> challenge 0: fix vercel deployments 

- packages/hardhat/test/Challenge3.ts
Changes:
Tests
1. Standardized the `rollAmount` across the entire test suite.
~~2.  Test `Should call diceGame.rollTheDice for a roll <= 5`~~
~~a. The `riggedRoll` function is now properly awaited.~~
b. ~~The `riggedRoll` function now  properly gets passed in a `msg.value`.~~
c. Removed nested `it` checks and moved their Chai checks to the end of the test.
d. Updated the `Roll` event check to have the proper amount of parameters and values.
> Challenge 3 dice game

- packages/nextjs/components/TransactionItem.tsx
- packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
It seems that we already solved #114 in SE-2 latest [`useTransactor`](https://github.com/scaffold-eth/scaffold-eth-2/blob/main/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx) just updated it here so that we show transaction notification when sending `execute` function 
https://github.com/scaffold-eth/se-2-challenges/assets/80153681/44569896-b38e-4c96-a43c-066062a56b4a
> update `useTransactor` to handle contract write

- packages/nextjs/components/ScaffoldEthAppWithProviders.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx
- packages/nextjs/styles/globals.css
- packages/nextjs/tailwind.config.js
Removed by mistake in https://github.com/scaffold-eth/se-2-challenges/pull/126
> fix: return space-grotesk font

- packages/nextjs/app/debug/_components/DebugContracts.tsx
- packages/nextjs/app/debug/_components/contract/ContractInput.tsx
- packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/Tuple.tsx
- packages/nextjs/app/debug/_components/contract/TupleArray.tsx
- packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/app/layout.tsx
- packages/nextjs/components/SwitchTheme.tsx
- packages/nextjs/components/ThemeProvider.tsx
- packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/NetworkOptions.tsx
- packages/nextjs/hooks/scaffold-eth/useAutoConnect.ts
- packages/nextjs/hooks/scaffold-eth/useBurnerWallet.ts
- packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts
- packages/nextjs/hooks/scaffold-eth/useScaffoldContract.ts
- packages/nextjs/package.json
- packages/nextjs/tailwind.config.js
- packages/nextjs/utils/scaffold-eth/contract.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
- yarn.lock
> feat: migrate next-theme

- packages/hardhat/test/Challenge3.ts
Just tried adding these changes manually to Autograder cloned challenge 3 and works great there too 🙌
<details>
<summary>
POST Request to new autograder: 
</summary>
```bash
curl -X POST http://localhost:54727 \
-H "Content-Type: application/json" \
-d '{"challenge": 3, "network": "sepolia", "address": "0x6Bbe593466EDfD15cbc33881F2C2131CB4c0081d"}'
```
</details>
verified contract: https://sepolia.etherscan.io/address/0x6Bbe593466EDfD15cbc33881F2C2131CB4c0081d#code
> Chall3: Make it autograder ready

- packages/hardhat/test/Challenge4.ts
Tested it both locally inside challenge and also on autotrader nothing breaks  🙌
> Chall4: Make it autograder ready

- packages/hardhat/test/Challenge5.ts
Does not break anything both locally while running test and on autograder also works nicely 🙌
> Chall5: Make it autograder ready

- README.md
- packages/nextjs/app/streamer/page.tsx
There are some typos in the receive functionality and in the docs.
> Challenge 5: Fix typo in receive functions and docs

- packages/nextjs/app/myNFTs/_components/NFTCard.tsx
fixes https://github.com/scaffold-eth/se-2-challenges/issues/172
before:
https://github.com/scaffold-eth/se-2-challenges/assets/25638585/e1053e3a-b9f2-4cc5-a444-f26bed992dc3
after:
https://github.com/scaffold-eth/se-2-challenges/assets/25638585/046aca85-4a55-4270-9c6f-cfad3c1fecd4
> Fix nft width

- README.md
- packages/hardhat/contracts/DEX.sol
https://docs.soliditylang.org/en/latest/style-guide.html#naming-styles
> Challenge 4 (DEX): use mixedCase for arg names in DEX.sol

- packages/nextjs/app/dex/page.tsx
> Challenge 4 (DEX): Add casts to `0x${string}` for appropriate vars in dex/page.tsx

- packages/hardhat/test/Challenge1.ts
I have fixed a typo in the Challenge 1 test file by replacing mintItem with stake
> fix: contract method

- packages/hardhat/.env.example
- packages/hardhat/hardhat.config.ts
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConfig.tsx
- packages/nextjs/utils/scaffold-eth/fetchPriceFromUniswap.ts
- packages/nextjs/utils/scaffold-eth/networks.ts
@technophile-04 mentioning you just to let you know I added challenge 1 fallback too
> Challenge 1 fallback

- packages/hardhat/.env.example
- packages/hardhat/hardhat.config.ts
- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/wagmiConfig.tsx
Reference https://github.com/scaffold-eth/scaffold-eth-2/pull/987
> Alchmey default

- extension/packages/nextjs/app/dice/page.tsx
Fixes https://github.com/scaffold-eth/se-2-challenges/issues/243
> fix: ch3 automining

- README.md
- extension/README.md.args.mjs
Add extra questions and updated solution snippets to check user balance and contract allowance before executing the transactions
Fixes #259
> Update readme to add checks for balance and allowance

- extension/README.md.args.mjs
Adding Readme changes to the template
> ch0 > Add vercel login to Readme template

- README.md
- extension/README.md.args.mjs
> Ch1 > Add vercel login info to README.md

- README.md
- extension/README.md.args.mjs
> Ch2 > Add vercel login info to README.md

- README.md
- extension/README.md.args.mjs
> Ch4 > Add vercel login info to README.md

- README.md
- extension/README.md.args.mjs
> Ch5 > Add vercel login info to README.md

- README.md
- extension/README.md.args.mjs
> Ch6 > Add vercel login info to README.md

- README.md
- extension/README.md.args.mjs
> Ch7 > Add vercel login info to README.md

- README.md
This updates the instructions to use extensions.
Related: https://github.com/scaffold-eth/se-2-challenges/pull/278
> Update contribution instructions for challenges as extensions

- extension/packages/hardhat/test/OverCollateralizedLending.ts
Adds 6 new tests to check requirements of the challenge description:
- Should require value of added collateral to be more than zero
- Should prevent withdrawing zero
- Should prevent withdrawing collateral if it makes the position liquidatable
- Should prevent borrowing when amount is zero
- Should prevent repaying when amount is zero
- Should have enough CORN to liquidate
Adds additional check for the liquidator's ETH balance to the "Should allow liquidation when position is unsafe" test.
> added additional tests to OverCollateralizedLending.ts

- README.md
We can merge this after we release https://github.com/scaffold-eth/create-eth/pull/256
> Collateralized lending readme command update

- extension/packages/hardhat/test/PredictionMarket.ts
Hi all,
I fixed the typo in test for autograder.
Thanks!
> fix typo for auto grader

- README.md
- extension/README.md.args.mjs
Removing the old (not recommended) transfer method per Austin's feedback.
Also updated the other call to revert with the appropriate error like other places in the contract.
> Removing old transfer method

- README.md
Hi @Pabl0cks,
This is continue for #303.
Some images on prediction markets challenge are not loading.
> fix: set absolute routes to readme images

- README.md
- extension/README.md.args.mjs
- extension/packages/nextjs/utils/getPoolServerUrl.ts
> Update multisig backend endpoint

- README.md
- extension/README.md.args.mjs
Just added suggested text from #338. I'll create similar for multisig when approved
Not sure which placing is better, before title, after title or after image. I've added it before title
> Svg nft build idea

- README.md
- extension/README.md.args.mjs
Just found out that Headings are not rendering well in SRE if they got bold styles in their text. 
Doing this quick PR here, but we could maybe check in SRE so it gets correctly rendered even with bold, just created an [issue ](https://github.com/BuidlGuidl/SpeedRunEthereum-v2/issues/326) there
> Delete bold styles from headings

- README.md
This PR just changes the wording for the first challenge.
> Change Simple NFT to Tokenization
