- README.md
- packages/nextjs/components/stake/StakeContractInteraction.tsx
- packages/nextjs/components/stake/index.tsx
- packages/nextjs/pages/stakerUI.tsx
- packages/nextjs/pages/stakings.tsx
It seems that the Staking UI was not updating when we were trying locally doing `yarn deploy --reset`
used [useBlockNumber](https://0.12.x.wagmi.sh/react/hooks/useBlockNumber) to forcefully refetch all the red variable once new block is added. 
I tried all the options for `useContractRead` but none work (as we also encountered here -> https://github.com/scaffold-eth/scaffold-eth-2/pull/177#issuecomment-1435948027 (seems a bit hacky but found this to be minimal / working nicely)
PS: For SE-2-chall we are still using v12 wagmi and here are its docs -> https://0.12.x.wagmi.sh/
Turns out the issue was related to wagmi cache problem, wagmi was using `cache` instead of refetching all the `read variables` (it does this until you hard refresh the page, or go to different tab and come back)
We …
> chall-1/fix wagmi cache issue on `deploy --reset`

- README.md
- packages/nextjs/components/Header.tsx
- packages/nextjs/components/stake/StakeContractInteraction.tsx
Fixes #28 
Changes the name of the events tab to Stake Events.
Updates readme to match that change.
Removes the 'left' from the second line in the Time Left section as it's redundant.
> Challenge 1 Wording Updates

- packages/nextjs/components/stake/StakeContractInteraction.tsx
- packages/nextjs/pages/debug.tsx
> challenge 1 betterments

- packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx
- packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx
- packages/nextjs/pages/dex.tsx
https://github.com/scaffold-eth/se-2-challenges/assets/80153681/17b0fbb2-dd2e-41e6-837e-77a9f49e8ad1
Fixes #44 
<details>
<summary>My Contract solution if anyone wants refer : </summary>
pragma solidity >=0.8.0 <0.9.0;
// SPDX-License-Identifier: MIT
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";
/**
* @title DEX
* @author stevepham.eth and m00npapi.eth
* @notice this is a single token pair reserves DEX, ref: "Scaffold-ETH Challenge 4" as per https://speedrunethereum.com/, README.md and full branch (front-end) made with lots of inspiration from pre-existing example repos in scaffold-eth organization.
*/
contract DEX {
/* ========== GLOBAL VARIABLES ========== */
uint256 public totalLiquidity; //total amount of liquidity …
> fix inputs breaks UI & update EtherInput to take in .number values

- README.md
Add extra explanations in README to `deposit()` and `withdraw()` functions, discussed in #58, and modify `Ship your contracts` section to delete screenshots and add `fromBlock` passed to `useScaffoldEventHistory` hint.
Complete list of changes:
- Remove side quest: `Side Quest: Prove your knowledge by calculating the exact amount of Balloons you need to approve when depositing. Don't forget about the fee!` (previously added in this PR)
- Explain in the Readme to add a high enough quantity to not have problems with allowance.
- Change description of `withdraw` like it is in last @Pabl0cks comment
> 💬💬 More Hints: The withdraw() function lets a user take his Liquidity Provider Tokens out, withdrawing both ETH and $BAL tokens out at the correct ratio.....
- Modify  `Ship your contracts` …
> Challenge 4 README - Deposit and Withdraw functions extra info, and modify Ship your contracts section

- README.md
- packages/hardhat/contracts/DEX.sol
This was reported on TG Dex chat : 
It seems that the autograder test checks expects (3rd argument) i.e index 2 as ethInput : 
https://github.com/scaffold-eth/scaffold-eth-challenges/blob/8b7c88f0a77d3487bb3a3b6ced792c8c1cee7cf4/packages/hardhat/test/constantProductTest.js#L131C1-L131C57
The reason for so is in SE-1-challenge we are logging `EthToTokenSwap` as : 
```solidity
emit EthToTokenSwap(msg.sender, "Eth to Balloons", msg.value, tokenOutput);
```
checkout [here](https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-4-dex#%EF%B8%8F-checkpoint-4-trading-), notice there is "Eth to Balloons" string in between which makes `msg.value`(ethInput) as 3rd argument 
--- 
Currently in SE-2 challenge Dex we don't have string parameter in between our event `EthToTokenSwap` only …
> Challenge 4: autograder test fail

- packages/hardhat/test/Challenge4.ts
Updated the test to match auto grader test so that people can run `yarn test` locally to see if it pass locally before submitting 🙌
--- 
I found that in SE-1 we are providing solution in repo here -> https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-4-dex/Solutions
Should we add similar solution code here too ? What do you all think ? 
Here is the solution code  : 
<details>
<summary>
Solution Code
</summary>
```
pragma solidity >=0.8.0 <0.9.0;
// SPDX-License-Identifier: MIT
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
/**
* @title DEX
* @author stevepham.eth and m00npapi.eth
* @notice this is a single token pair reserves DEX, ref: "Scaffold-ETH Challenge 4" as per https://speedrunethereum.com/, README.md and full branch (front-end) made with lots of …
```
> fix test to match autograder test

- packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
- packages/nextjs/hooks/scaffold-eth/useScaffoldEventSubscriber.ts
- packages/nextjs/pages/stakings.tsx
Events table doesn't work if when creating a contract, `Stake` event parameters aren't named `staker` and `amount`. In base Challenge contract params of `Stake` event has no names, also in [Readme](https://github.com/scaffold-eth/se-2-challenges/blob/challenge-1-decentralized-staking/README.md?plain=1#L9) too.
So we need to use [0] and [1] args by default.
> fix: stake events frontend

- packages/nextjs/pages/dice.tsx
On small screen dice page shows roll event, winner event and game ui in single row, making events UI to overlap with center game UI. 
On small screen dice page will show Game UI on top and then roll event and then winner event in stack form. 
When screen size is small reduce the grid column to 1 and rearrange Game UI, Roll Event and Winner UI with grid's start-row property.
> stack roll events and dice roll content on small screen

- packages/nextjs/components/scaffold-eth/Address.tsx
Currently copy icon of address component uses custom light blue color but this cause issue when some custom background is used. The issue is icon not clearly visible against some background.
Change copy icon of address component to not use custom icon color but keep it default so that it auto adjust against background.
Remove custom tailwind css text property.
Test method - add a new address component in debug tab under contact variable so see different against 3 different background.
> don't use custom light blue color for copy icon

- README.md
- packages/hardhat/contracts/DEX.sol
- packages/hardhat/test/Challenge4.ts
Fixed the Liquidity provided test by adding 1 wei unit to the expected number of tokens deposited.
When calculating the tokens added when depositing liquidity, we add 1 wei as a safeguard. As the solution code demonstrates in Checkpoint 5 here: https://speedrunethereum.com/challenge/minimum-viable-exchange
```
tokenDeposit = (msg.value * tokenReserve / ethReserve) + 1;
// 💡 Discussion on adding 1 wei at end of calculation   ^
// -> https://t.me/c/1655715571/106
```
However, adding 1 as above breaks the test that checks the `LiquidityProvided` event for the added tokens.
Fixed the test by adding one wei to the expected number of tokens deposited.
- Clone the repo
- Checkout the branch `challenge-4-dex`
- Copy all the solution code from the README into DEX.sol
- Implement the `getLiquidity` …
> Fix test on token liquidity added to DEX

- README.md
Commented [here](https://github.com/scaffold-eth/se-2-challenges/issues/117#issuecomment-1889601235), adding a reference to our deployed backend url when the Challenge is deployed to chains different than Hardhat.
> Add reference to our deployed backend url for chains different than Hardhat

- packages/hardhat/test/Challenge0.ts
- Contracts are downloaded from the autograder and run locally.
- Had to add the prefix "download", if not getting this (typechain to blame, doesn't like the files starting with numbers.)
If doesn't affect the test workflow for the builder, we can merge it.
We need to do this for all the other challenges too. SE-1 tests did this too (e.g. https://github.com/scaffold-eth/scaffold-eth-challenges/blob/challenge-1-decentralized-staking/packages/hardhat/test/challenge_1.js), but not sure why/when we changed it in the SE-2.
> Ch0: Update test for the autograder

- README.md
- packages/hardhat/contracts/Vendor.sol
Within `Checkpoint 2: ⚖️ Vendor 🤖`, the instruction `Edit Vendor.sol to inherit Ownable` assumes that the Vendor contract isn't already Ownable. Therefore, the Vender contract should not inherit the Ownable contract by default. Instead, the user should update the contract to inherit the Ownable contract when the instruction `Edit Vendor.sol to inherit Ownable` is reached.
> Removed ownable from contract

- packages/nextjs/vercel.json
Vercel now uses npm install by default and we get this :
> add vercel.json with mention installCommand

- packages/nextjs/app/api/ipfs/add/route.ts
- packages/nextjs/app/api/ipfs/get-metadata/route.ts
I am sure but for some reason, certain people are facing this issue, when they click "Mint NFT" btn  : 
<details>
<summary>Error Image from TG chat</summary>
</details>
This doesn't happen to me and everything works fine for me, but a couple of people in the challenge 0 TG group faced this [1](https://t.me/c/1716981265/4190), [2](https://t.me/c/1716981265/4145)
Its mainly caused due infura and ipfs cilent not working properly for certain region / using VPN kind of related discussion on [infura](https://community.infura.io/t/ipfs-add-not-working/1554/4)
Neverthe less this PR wraps the api in try catch, so that atleast we are able to see cards on frontend ( although without NFT image) but people can move forward and submit the challenge it does not block them
> Wrap api in try catch for chall 0

- README.md
Within the documentation in README.md, there were 2 instances of variable redeclarations. These redeclarations simply cause a warning and will still allow the code to compile.
```
function ethToToken() public payable returns (uint256 tokenOutput) {
require(msg.value > 0, "cannot swap 0 ETH");
uint256 ethReserve = address(this).balance - msg.value;
uint256 token_reserve = token.balanceOf(address(this));
uint256 tokenOutput = price(msg.value, ethReserve, token_reserve); // tokenOutput redeclared
require(token.transfer(msg.sender, tokenOutput), "ethToToken(): reverted swap.");
emit EthToTokenSwap(msg.sender, tokenOutput, msg.value);
return tokenOutput;
}
...
function tokenToEth(uint256 tokenInput) public returns (uint256 ethOutput) {
require(tokenInput > 0, "cannot swap 0 tokens");
uint256 …
```
> Remove variable redeclarations

- README.md
Last couple of weeks I've been researching different approaches to create an assistant to help new SRE users through their Challenges. I've tried:
- __Fine tunning a model with SE-2 docs, Challenge 0 Readme and TG Challenge 0 Q/A.__
Didn't work at all, probably didn't do it right because results were terrible. Could try again in the future with a different base model, but this system requires to develop also a layer to interact with the users (web, telegram bot)
- __Using a local AI (PrivateGPT) as a solution to privacy concerns, giving it contexts (SE-2 docs, Challenge 0 Readme and TG Challenge 0 Q/A).__
You don't share all your info and the user prompts and answers with a 3rd party, and there is no limit of context to provide, but I don't see an easy solution to open it to the users nor …
> Add a link to the alpha version of Ch0 assistant at Readme

- README.md
* Update mentions of `01_deploy_vendor.js` to `01_deploy_vendor.ts`
* These scripts are now TypeScript files and this provides more clear instructions
> fix: update deployment script names to match latest

- packages/nextjs/app/dice/_components/WinnerEvents.tsx
- packages/nextjs/app/dice/page.tsx
- **Mark `args.player` as `viem/Address`** - fixes this error:
- **Convert `Winner.address` type from `string` to `viem/Address`** - more accurate
- **Mark `args.winner` as `viem/Address`** - similar to first point
> Challenge 3 (Dice Game): Fix address-related errors/warnings

- packages/hardhat/contracts/MetaMultiSigWallet.sol
- use `call` instead of `transfer` for sending ETH
- format code
> Minor refactor to MetaMultiSigWallet.sol

- extension/packages/hardhat/deploy/00_deploy_contracts.ts
This just adds a check to see if the deployment is local so that we can avoid running the `hardhat_setBalance` methods when deploying to a real network. Ran into this yesterday while testing. I am inclined just to merge it since it is simple but I will let you guys check my logic as well.
Without this it still deploys fine but it gives a nasty error when it tries to use the `hardhat_setBalance` method on a real RPC.
> only set contract state when on hardhat chain

- extension/packages/hardhat/scripts/marketSimulator.ts
When running simulation experienced many liquidation errors. The reason is that everyone is included in the eligibleLiquidators list without checking CORN balance required for liquidation.
Added additional check for eligibleLiquidators to include only ones who have enough CORN to liquidate.
> Filters liquidators to include only those who have enough corn balance

- README.md
- extension/README.md.args.mjs
This addresses feedback from Austin, Zak and some Batch members who tested the challenge.
- Reframed to talk about collateral value going down instead of borrowed asset value going up
- Using `yarn deploy --reset` as a shortcut to restarting `yarn chain` and then `yarn deploy`ing
- Made the position of `_validatePosition` more clear
- Updates the challenge name to `challenge-over-collateralized-lending` per  conversation on https://github.com/scaffold-eth/create-eth/pull/252
- Adds note about using hardhat/console to help students get through tricky parts
- Gives instructions on how to manipulate the price using the controls on the front end
- Provided more clarity about what the `liquidate` function is meant to achieve before giving specific steps
- Added clarity around the fact that the …
> Update README for clarity

- README.md
- extension/README.md.args.mjs
- extension/packages/nextjs/app/page.tsx.args.mjs
To test 
```
npx create-eth@0.2.3 -e https://github.com/scaffold-eth/se-2-challenges/tree/fix-main-page challenge-over-collateralized-lending
```
Add all the contracts and deployment code (copy-paste from solutions on the challenge page)
Run
```
yarn next:build
```
You shouldn't see main page build error. The only build error should be this
```
✓ Compiled successfully
Linting and checking validity of types  ...Failed to compile.
./services/web3/wagmiConnectors.tsx:35:7
Type error: Type '((({ projectId, walletConnectParameters, }: DefaultWalletOptions) => Wallet) | (({ projectId, options, }: WalletConnectWalletOptions) => Wallet) | CoinbaseWallet | RainbowkitBurnerWallet)[]' is not assignable to type 'CreateWalletFn[]'.
...
```
which will be fixed after updating `burner-connector` version …
> Fix ocl main page build

- extension/packages/nextjs/app/dashboard/_components/CollateralGraph.tsx
A user in telegram reported this issue where deploying to Vercel was not happening due to this error:
https://t.me/c/2648952355/20
This change should resolve the linter error and allow deployment to Vercel.
I tested it and was able to successfully deploy to Vercel. Also everything worked as expected with the collateral graph.
> remove "in" due to parser/linter issues in Vercel deployment

- README.md
- extension/README.md.args.mjs
- extension/packages/hardhat/contracts/Corn.sol
- extension/packages/hardhat/test/Lending.ts
Somebody recently reported some issues with this challenge. This is all related to some changes we pushed through after Austin had some feedback a few weeks ago. The side quests would not work with the new changes. 
In addition to this it seems a test was also not updated (I am surprised by this since I am sure we would have run them when we made the changes).
We need to update the autograder with the new test as well.
Here is a contract that matches what the README give the user: https://sepolia.etherscan.io/address/0xE543ac072299c4222dECa0BbdFFC8fd551f15649#code
> Fix: update borrowing and flash loan logic in README
